# Generated by Django 3.1 on 2020-08-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200812_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
