# Generated by Django 3.1 on 2020-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200813_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
